x <- readRDS("data/sim_minority_extension_cache.rds")
cat("nrow:", nrow(x$data), "\n")
tab <- table(x$data$condition, x$data$r_ingroup, x$data$r_background)
cat("dim:", paste(dim(tab), collapse=" x "), "\n")
cat("total nonzero cells:", sum(tab > 0), "expected cells:", 3*5*3, "\n")
cat("min/max cell count:", min(tab), max(tab), "\n")
cat("seed range:", range(x$data$seed), " unique seeds:", length(unique(x$data$seed)), "\n")
cat("any NA total_components:", sum(is.na(x$data$total_components)), "\n")
cat("any NA cross_group_dlg_rate:", sum(is.na(x$data$cross_group_dlg_rate)), "\n")
cat("any NA cdr_min_to_maj:", sum(is.na(x$data$cdr_min_to_maj)), "\n")
